name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Generate
      run: cargo run --package rustle --bin generate_xqts
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test --verbose
