name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        rust_channel: ["nightly"]
    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Submodules
      run: git submodule update --init --recursive
    - name: Install rustup
      run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile=minimal
    - name: Install rust channel
      run: |
        rustup install ${{matrix.rust_channel}}
        rustup default ${{matrix.rust_channel}}
    - name: Generate
      run: RUSTFLAGS=-Awarnings cargo run --package rustle --bin generate_xqts
    - name: Build
      run: cargo build
    - name: Run tests
      run: |
        cargo install cargo2junit;
        RUSTFLAGS=-Awarnings cargo test --release -- -Z unstable-options --format json --report-time | cargo2junit > results.xml;
    - name: Upload test results
      uses: EnricoMi/publish-unit-test-result-action@v1
      with:
        check_name: Test Results
        github_token: ${{ secrets.GITHUB_TOKEN }}
        files: results.xml
